# Generated by Django 4.1 on 2022-08-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
