# Generated by Django 4.1 on 2022-08-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_employee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='emp/images'),
        ),
    ]
